### ISSUE TITLE
Add different lastmod to each query_param?

### ISSUE THREAD

**Issue by turtleship69** [sjquant/sitemapr#13]
Hi, I found this library and it's been really helpful, however I was wondering if it's possible to have a different lastmod value for each query_param combo.  
My website has URLs in the format `/post?p={id}`, and I have a list of IDs and the dates they were posted. Currently I have: 
```
Page(
    path='/posts',
    query_params=[
        Param(name="p", values=posts),
    ]
)
```
and a list called dates. 
Is there any way add the corresponding dates to the post IDs without having to reimplement the entire logic for the params. 
Thanks

**Comment by sjquant** [comment]
@turtleship69 

Thanks for the comment. Currently it's impossible. but I'm going to implement it soon.

**Comment by sjquant** [comment]
@turtleship69

Now, you can install v0.3.0 to use that feature.

**Comment by turtleship69** [comment]
@sjquant 
Thank you so much 
How would I use this with the code from the original message?

**Comment by sjquant** [comment]
> @sjquant Thank you so much How would I use this with the code from the original message?

You can do like this:

```py
def postid_to_lastmod(postid: str) -> str:
    # logic to lastmod for post id
    return lastmod

Page(
    path='/posts',
    query_params=[
        Param(name="p", values=posts),
    ],
    lastmod=lambda loc, path_params, query_params: postid_to_lastmod(query_params["id"])
)
```

**Comment by turtleship69** [comment]
Yep, this works like a charm, thanks!
